name: PortalCalc
version: 1.2.0
main: me.psanker.portalcalc.PCMain

commands:
  pcalc:
    description: Calculate coords (nether or overworld)
    usage: |
      /<command> [-n, -o, -s, scan, -h, help]
  pc:
    description: Alias for /pcalc
    usage: |
      /<command> [-n, -o, -s, scan, -h, help]