name: PortalCalc
version: 1.0.1
main: me.psanker.portalcalc.PCMain

commands:
  pcalc:
    description: Calculate coords (nether or overworld)
    usage: |
      /<command> [-n, -o, -h, help]
  pc:
    description: Alias for /pcalc
    usage: |
      /<command> [-n, -o, -h, help]