name: PortalCalc
version: 1.3.0a
main: me.psanker.portalcalc.PCMain
database: true

commands:
    pcalc:
        description: Main command
        usage: |
              /<command> [-n, -o, -s, scan, -h, help, -v]
    pc:
        description: Main command
        usage: |
              /<command> [-n, -o, -s, scan, -h, help, -v]
